#!/bin/bash
v2rayinst() {
		[[ -e "/bin/v2ray" ]] && {
		    clear
			v2raymanager
		} || {
			cd $HOME
			source <(curl -sL https://raw.githubusercontent.com/src-dpmfd/Jdvdidhdisndujsjdivd/main/v2ray) -o /dev/null
			chmod 777 v2ray
			./v2ray 
			clear
			v2raymanager
		}

	}
slow_setup() {
		[[ -e "/bin/slowdns" ]] && { 
		    clear
			slowdns
		} || {
			cd $HOME
			wget https://raw.githubusercontent.com/src-dpmfd/Jdvdidhdisndujsjdivd/main/install -o /dev/null
			chmod 777 install
			./install
		}

	}
display_active_services_lsof() {
    if ! command -v lsof &> /dev/null; then
        echo -e "\033[01;31m║\033[1;33m Instalando 'lsof' para verificação de serviços... \033[0m"
        (apt-get update -y && apt-get install -y lsof) > /dev/null 2>&1
    fi

    local PT
    PT=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" | grep -v "COMMAND" | grep "LISTEN")
    
    if [[ -z "$PT" ]]; then
        echo -e "\033[01;31m║\033[1;33m Nenhum serviço de rede ativo detectado pelo lsof.\033[0m"
        return
    fi
    
    for porta in $(echo -e "$PT" | cut -d: -f2 | cut -d' ' -f1 | uniq); do
        local svcs

        svcs=$(echo -e "$PT" | grep -w "$porta" | awk '{print $1}' | uniq | tr '\n' ' ')

        echo -e "\033[01;31m║\033[1;33m SERVIÇO: \033[1;37m${svcs% } \033[1;33mPORTA: \033[1;37m$porta"
    done
}
x="ok"
fun_conexao() {
    while true; do
        [[ ! -e '/home/sshplus' ]] && exit 0
        clear
			xv2ray=`if netstat -tunlp |grep v2ray 1> /dev/null 2> /dev/null; then
			echo -e "\033[1;32m◉ "
			else
			echo -e "\033[1;31m○ "
			fi`;
			clear
			var_sks1=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
			clear 
			echo -e ""
			[[ -e "/etc/stunnel/stunnel.conf" ]] && {
				sts3="\033[1;32m◉ "
			} || {
				sts3="\033[1;31m○ "
			}
        echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\E[41;1;37m    ⇱         SSHPLUS  by: @alfalemos        ⇲    \E[0m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    display_active_services_lsof
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mWEBSOCKET \033[1;31m                [\033[1;36m11\033[1;31m] \033[1;37m• \033[1;33mPROXY DRAGON \033[1;31m
[\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mPROXY RUST \033[1;31m               [\033[1;36m12\033[1;31m] \033[1;37m• \033[1;33mPROXY DT V1 \033[1;31m
[\033[1;36m03\033[1;31m] \033[1;37m\033[1;37m• \033[1;33mSSL TUNNEL $sts3\033[1;31m             [\033[1;36m13\033[1;31m] \033[1;37m• \033[1;33mPROXY DT V2 \033[1;31m
[\033[1;36m04\033[1;31m] \033[1;37m• \033[1;33mBADVPN PRO 2 ALFA $var_sks1\033[1;31m      [\033[1;36m14\033[1;31m] \033[1;37m• \033[1;33mBADVPN PRO KIRITO $var_sks1\033[1;31m
[\033[1;36m05\033[1;31m] \033[1;37m• \033[1;33mSLOWDNS \033[1;31m                  [\033[1;36m15\033[1;31m] \033[1;37m• \033[1;33mV2RAY $xv2ray\033[1;31m
[\033[1;36m06\033[1;31m] \033[1;37m• \033[1;33mRESOLVEDOR LOCAL\033[1;31m          [\033[1;36m16\033[1;31m] \033[1;37m• \033[1;33m(HTOP) \033[1;31m
[\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mCHECKUSER DTUNNEL \033[1;31m        [\033[1;36m17\033[1;31m] \033[1;37m• \033[1;33mMENU \033[1;31m>\033[1;33m>\033[1;32m>\033[0m\033[1;31m
[\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mCHECKUSER 4G \033[1;31m             [\033[1;36m18\033[1;31m] \033[1;37m• \033[1;33mSAIR \033[1;32m<\033[1;33m<\033[1;31m<\033[1;31m
[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mMEMÓRIA VIRTUAL \033[1;31m    
[\033[1;36m10\033[1;31m] \033[1;37m• \033[1;33mCHECKUSER MODS\033[1;31m              
\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
			echo ""
			tput civis
			echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m "
			read x
			tput cnorm
			clear
			case $x in
			1 | 01) 
			clear
			wsmenu
				;;
			2 | 02)
			clear
			proxyrust
				;;
			3 | 03)
			clear
			stunnel2
				;;
			4 | 04)
			clear
			badvpn.sh
				;;
			5 | 05)
			clear
			slow_setup
				;;
			6 | 06)
			clear
			dnsserv
				;;
			7 | 07)
			clear
			menu_check
				;;
			8 | 08)
			wget -O /etc/rec/licence "https://raw.githubusercontent.com/sofrenoob/Gggggg/refs/heads/main/h/sshplus/Modulos/licence" -o /dev/null
			clear
			initcheck
				;;
			9 | 09)
			clear
			swapmemory.sh
				;;
			    10)
			    clear 
			    chuker.sh
				;;
			    11)
			    clear
			    proxyd
				;;
			    12)
			    clear
			    proxydtv1
			    ;;
		        13)
		        clear
		        proxydtv2
				;;
			    14)
			    wget -O /etc/rec/licence "https://raw.githubusercontent.com/sofrenoob/Gggggg/refs/heads/main/h/sshplus/Modulos/licence" -o /dev/null
			    clear
			    badvpn
				;;
			    15)
			    clear
			    v2rayinst
				;;
			    16)
			    clear
			    htop
				;;
			    17)
			    clear
			    menu
				;;
			    18)
			    echo -e "\033[1;31mSaindo...\033[0m"
			    sleep 1
			    clear
			    exit
				;;
	     		*)
	     		echo -e "\033[1;31mOpcao invalida !\033[0m"
	     		sleep 1
	     		clear
				;;
			esac
		done
}
fun_conexao