#!/bin/bash
check_htop() {
    if ! command -v htop > /dev/null 2>&1; then
        echo -e "\033[1;33mO 'htop' não está instalado. Instalando agora...\033[0m"
        apt-get update > /dev/null 2>&1
        apt-get install -y htop > /dev/null 2>&1
        echo -e "\033[1;32m'htop' instalado com sucesso!\033[0m"
        sleep 2
    fi
}

ver_htop() {
    check_htop
    clear
    echo -e "\E[44;1;37m         MONITOR DE PROCESSOS (HTOP)         \E[0m"
    echo ""
    echo -e "\033[1;33mO monitor de processos será iniciado em 4 segundos...\033[0m"
    echo ""
    echo -e "\033[1;37m➡️  Pressione a tecla '\033[1;32mq \033[1;37m' ou \033[1;32mCTRL+C \033[1;37m para sair e voltar ao menu."
    echo ""
    sleep 4

    htop
}

menu() {
    clear
    echo -e "\E[44;1;37m        MONITOR DE PROCESSOS (HTOP)       \E[0m"
    echo ""
    echo -e "\033[1;33mSelecione uma opção abaixo:\033[0m"
    echo ""
    echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mVer Processos do Sistema \033[0m"
    echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mSAIR\033[0m"
    echo ""
    echo -ne "\033[1;32mO QUE DESEJA FAZER \033[1;33m?\033[1;37m "
    read opcao

    case $opcao in
        1)
            ver_htop
            ;;
        0)
            clear
            echo -e "\033[1;32mSaindo...\033[0m"
            clear
            menu.sh 0
            ;;
        *)
            echo -e "\n\033[1;31mOpção inválida! Tente novamente.\033[0m"
            sleep 2
            ;;
    esac
}

if [[ $EUID -ne 0 ]]; then
   echo -e "\033[1;31mEste script precisa ser executado como root (use sudo).\033[0m" 
   exit 1
fi

while true; do
    menu
done